#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "koel"
name = "Koel"
description.en = "Simple web-based personal audio streaming service"
description.fr = "Simple service web de streaming audio personnel"

version = "7.8.1~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
website = "https://koel.dev"
demo = "https://demo.koel.dev"
admindoc = "https://docs.koel.dev"
code = "https://github.com/koel/koel"
cpe = "cpe:2.3:a:koel:koel"

fund = "https://opencollective.com/koel"

[integration]
yunohost = ">= 11.2.29"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/koel/koel/releases/download/v7.8.1/koel-v7.8.1.tar.gz"
    sha256 = "fbf82f617b5a4c87b680f4c57d6b0a2a444b198c584c7457f51c2bc13776a611"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "^koel-v.*tar.gz$"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = [
        "php8.2-fpm",
        "php8.2-gd",
        "php8.2-mbstring",
        "php8.2-mysql",
        "php8.2-sqlite3",
        "php8.2-xml",
        "mariadb-server",
        "ffmpeg",
    ]

    [resources.database]
    type = "mysql"
