#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "koel"
name = "Koel"
description.en = "Simple web-based personal audio streaming service"
description.fr = "Simple service web de streaming audio personnel"

version = "7.0.12~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
website = "https://koel.dev"
demo = "https://demo.koel.dev"
admindoc = "https://docs.koel.dev"
code = "https://github.com/koel/koel"
cpe = "cpe:2.3:a:koel:koel"
fund = "https://opencollective.com/koel"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/koel/koel/releases/download/v7.0.12/koel-v7.0.12.tar.gz"
    sha256 = "d56921b243954b4fcc0b03caa880e85179caf71ed1a0cdc5ef9893ddb2432bbd"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "^koel-v.*tar.gz$"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php8.2-fpm",
        "php8.2-gd",
        "php8.2-mbstring",
        "php8.2-mysql",
        "php8.2-sqlite3",
        "php8.2-xml",
        "mariadb-server",
        "ffmpeg",
    ]

    [resources.database]
    type = "mysql"
