#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "koel"
name = "Koel"
description.en = "A simple web-based personal audio streaming service written in Vue on the client side and Laravel on the server side. Targeting web developers, Koel embraces some of the more modern web technologies to do its job."
description.fr = "Un simple service web de streaming audio personnel, écrit en Vue pour le client et en Laravel pour le serveur. Destiné aux développeurs web, Koel utilise certaines des technologies web les plus modernes pour accomplir son travail."

version = "6.11.2~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
website = "https://koel.dev"
demo = "https://demo.koel.dev"
admindoc = "https://docs.koel.dev"
code = "https://github.com/koel/koel"
cpe = "cpe:2.3:a:koel:koel"
fund = "https://opencollective.com/koel"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/koel/koel/releases/download/v6.11.2/koel-v6.11.2.tar.gz"
        sha256 = "db344b927be7a403712c3f4198288c01792dd1dc54af9b76b4ea16d6e62e5dc7"

        autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    allow_email = true
    
    [resources.install_dir]

    [resources.data_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-fpm, php8.2-mysql, php8.2-sqlite3, mariadb-server, ffmpeg"

    [resources.database]
    type = "mysql"
